[build]
  command = "pip install --no-cache-dir -r requirements.txt && echo 'Listing static files...' && ls -l static/ || echo 'No files in static/'; echo 'Build complete.'"
  publish = "static"
  functions = "api"
  environment = { PYTHON_VERSION = "3.8" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
