[build]
  command = "pip install --no-cache-dir -r requirements.txt && mkdir -p static && cp -r static/* static/ || true"
  publish = "static"
  functions = "api"
  environment = { PYTHON_VERSION = "3.8" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
